### ISSUE TITLE
Initial logo for the club

### ISSUE THREAD

**Issue by vlopezj** [InitialTypes/Club#1]
A provisional avatar for the Initial Types Club!

<img src="https://user-images.githubusercontent.com/1593773/33212612-4a1aa350-d124-11e7-95cf-b421baf74cd5.png" width=128>

I think it is less bland than the current one:

<img src="https://user-images.githubusercontent.com/1593773/33212506-b7a4a0ac-d123-11e7-8104-d308aed7eb5e.png" width=128>

**Comment by andreasabel** [comment]
We could also use \bot for the empty type.

**Comment by andreasabel** [comment]
@vlopezj : Ah, can we get the logo with transparent background?

**Comment by superhaNds** [comment]
A zero with a diagonal line could also work; I've seen it represent the initial object.

**Comment by andreasabel** [comment]
Yes, but it looks suspiciously like the empty set.  (We need to distinguish ourselves from set theory. ;-))

**Comment by vlopezj** [comment]
@andreasabel Sure! Here it is:
<img alt="the-logo-transparent.png" width=128 src="https://user-images.githubusercontent.com/1593773/33265014-3246a7bc-d370-11e7-9362-4ae2fed5edfb.png" />

**Comment by andreasabel** [comment]
Thanks!
