### ISSUE TITLE
Agda resources: examples of coinduction and equational reasoning

### ISSUE THREAD

**Issue by Zalastax** [InitialTypes/Club#3]
I'm looking for good intermediate level resources for Agda. Verified Functional Programming in Agda is one example. Do you know of some open source code that uses a good Agda style?

Two topics that I'm especially interested in are writing equational reasoning style proof (EqReasoning), and coinduction.
For coinduction I would like to see how to implement [these tricks](https://www.techrepublic.com/article/infinite-list-tricks-in-haskell/) in Agda.

**Comment by andreasabel** [comment]
I have a draft here that uses coinduction to define tries: http://www.cse.chalmers.se/~abela/jlamp17.pdf
It uses a lot of equational reasoning, in combination with coinduction.

The standard library is _some open source code that uses a good Agda style_, however, it does not use copatterns.  Yet you can find instances of equational reasoning.
